openapi: 3.0.0
info:
  title: Simple Inventory API
  description: This is a simple API
  contact:
    email: you@your-company.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: http://func.localhost
  description: Local az func fancy routing
- url: http://localhost:7071
  description: Local az func
paths:
  /api/matchHistory:
    get:
      summary: Gets a match or all matches from a player
      parameters:
      - name: gameId
        in: query
        required: false
        schema:
          type: number
          format: integer
      - name: uid
        in: query
        required: false
        schema:
          type: string
      responses:
        "200":
          description: "success"

    post:
      summary: Create match history
      parameters:
      - name: a
      responses:
        "200":
          description: "success"
          # content:
          #   application/json:
          #     schema:
          #       $ref: '#/components/schemas/Student'

components:
  # schemas:
  #   Student:
  #     required:
  #     - first_name
  #     - last_name
  #     type: object
  #     properties:
  #       student_id:
  #         type: number
  #         format: integer
  #       first_name:
  #         type: string
  #       last_name:
  #         type: string
  #         example: Coltof
  #       gradeRecords:
  #         type: array
  #         items:
  #           $ref: '#/components/schemas/GradeRecord'
  #     example:
  #       first_name: Quinten
  #       last_name: Coltof
  #       gradeRecord:
  #       - 8
  #       - 9
  #       - 10
  #   GradeRecord:
  #     required:
  #     - grade
  #     - subject_name
  #     type: object
  #     properties:
  #       subject_name:
  #         type: string
  #       grade:
  #         maximum: 10
  #         minimum: 0
  #         type: number
  #         format: float
  #     example:
  #       subject_name: Quinten Coltof
  #       grade: 10

