IF OBJECT_ID('users', 'U') IS NOT NULL
BEGIN
  DROP TABLE users;
END;


CREATE TABLE users (
  id INT IDENTITY(1,1) PRIMARY KEY,
  userName VARCHAR(50) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  games_won INT NOT NULL DEFAULT 0,
  games_lost INT NOT NULL DEFAULT 0,
  games_played INT NOT NULL DEFAULT 0,
  admin BIT NOT NULL DEFAULT 0
);
