
name: Deploy GameEngine

on:
  push:
    branches:
    - dev
    paths:
      - src/GameEngine/**
  workflow_dispatch:

# gh workflow run GameEngine-deploy.yml --ref dev

jobs:
  call-workflow-passing-data:
    uses: ./.github/workflows/deploy-template.yml
    with:
      AZURE_FUNCTIONAPP_PACKAGE_PATH: 'src/GameEngine'
      RESOURCE_GROUP_NAME_DEV: 'rg-someroc-dev'
      RESOURCE_FUNCTIONAPP_NAME_DEV: 'func-someroc-gameEngine-dev'
    secrets: inherit
